### ISSUE TITLE
Windows按照文档步骤run:wechat没问题，run:alipay、run:swan报错

### ISSUE THREAD

**Issue by Seansun1314** [kaola-fed/megalo#109]
### run:wechat没问题，run:alipay、run:swan报错
我的node: v11.0.0，npm: v3.8.6
megalo新建的时候有如下警告：
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4`
`npm WARN @megalo/target@0.4.10 requires a peer of @babel/core@^7.1.6 but none was installed`

**以下是具体报错：**
`PS E:\Definesys\Projects\小程序组件封装\my-megalo> npm run dev:alipay`

`> my-megalo@0.0.0 dev:alipay E:\Definesys\Projects\小程序组件封装\my-megalo`
`> webpack --config ./build/webpack.config.alipay.js -w`

`webpack is watching the files…`

`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\@megalo\target\lib\platforms\shared\utils\composePlatformConfig.js:5:6)
    at Object.module.exports [as json] (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\@megalo\target\lib\platforms\alipay\codegen\page.json.js:8:19)
    at forEach.type (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\@megalo\target\lib\platforms\shared\index.js:35:45)
    at Array.forEach (<anonymous>)
    at pages.forEach.options (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\@megalo\target\lib\platforms\shared\index.js:34:50)
    at Array.forEach (<anonymous>)
    at E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\@megalo\target\lib\platforms\shared\index.js:26:11
    at compiler.hooks.emit.tap.compilation (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\@megalo\target\lib\plugins\MegaloPlugin.js:96:7)
    at _err0 (eval at create (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:14:1)
    at callback (E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\copy-webpack-plugin\dist\index.js:77:17)
    at E:\Definesys\Projects\小程序组件封装\my-megalo\node_modules\copy-webpack-plugin\dist\index.js:118:24`

`npm ERR! Windows_NT 10.0.10240
npm ERR! argv "E:\\Definesys\\node6.1.0\\node.exe" "E:\\Definesys\\node6.1.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev:alipay"
npm ERR! node v11.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! my-megalo@0.0.0 dev:alipay: webpack --config ./build/webpack.config.alipay.js -w
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-megalo@0.0.0 dev:alipay script 'webpack --config ./build/webpack.config.alipay.js -w'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-megalo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config ./build/webpack.config.alipay.js -w
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-megalo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-megalo
npm ERR! There is likely additional logging output above.`

`npm ERR! Please include the following file with any support request:
npm ERR!     E:\Definesys\Projects\小程序组件封装\my-megalo\npm-debug.log`
![Uploading image.png…]()`

**Comment by elcarim5efil** [comment]
请更新一下再试试：
megalo@0.6.3
@megalo/template-compiler@0.6.3
@megalo/target@0.5.5

**Comment by Seansun1314** [comment]
ok，升级以后成功解决，非常感谢！

**Comment by JH46666** [comment]
你好，我也有问哥问题，npm重新安装后出现这个

webpack is watching the files…

TypeError: Cannot read property 'tag' of undefined
    at visit (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4666:21)
    at walk (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4672:3)
    at mpify (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4655:3)
    at baseCompile (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:5069:3)
    at compile (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4331:22)
    at Object.compileToTemplate$1 [as compileToTemplate] (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:6010:18)
    at Object.module.exports [as component] (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/platforms/wechat/codegen/component.js:2:19)
    at Object.keys.forEach.resourcePath (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/platforms/shared/index.js:73:38)
    at Array.forEach (<anonymous>)
    at /Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/platforms/shared/index.js:56:30
    at compiler.hooks.emit.tap.compilation (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/plugins/MegaloPlugin.js:201:7)
    at _err0 (eval at create (/Users/sjh/Documents/tell2.0_megalo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:14:1)
    at callback (/Users/sjh/Documents/tell2.0_megalo/node_modules/copy-webpack-plugin/dist/index.js:77:17)
    at /Users/sjh/Documents/tell2.0_megalo/node_modules/copy-webpack-plugin/dist/index.js:118:24
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tell2.0_megalo@0.0.0 dev:wechat: `webpack --config ./build/webpack.config.wechat.js -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tell2.0_megalo@0.0.0 dev:wechat script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sjh/.npm/_logs/2019-01-11T00_47_45_689Z-debug.log
➜  [/Us
