### ISSUE TITLE
npm重新安装后，run:wechat报错

### ISSUE THREAD

**Issue by JH46666** [kaola-fed/megalo#121]
你好，我也有问问题，npm重新安装后出现这个

webpack is watching the files…

TypeError: Cannot read property 'tag' of undefined
    at visit (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4666:21)
    at walk (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4672:3)
    at mpify (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4655:3)
    at baseCompile (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:5069:3)
    at compile (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:4331:22)
    at Object.compileToTemplate$1 [as compileToTemplate] (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/template-compiler/build.js:6010:18)
    at Object.module.exports [as component] (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/platforms/wechat/codegen/component.js:2:19)
    at Object.keys.forEach.resourcePath (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/platforms/shared/index.js:73:38)
    at Array.forEach (<anonymous>)
    at /Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/platforms/shared/index.js:56:30
    at compiler.hooks.emit.tap.compilation (/Users/sjh/Documents/tell2.0_megalo/node_modules/@megalo/target/lib/plugins/MegaloPlugin.js:201:7)
    at _err0 (eval at create (/Users/sjh/Documents/tell2.0_megalo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:14:1)
    at callback (/Users/sjh/Documents/tell2.0_megalo/node_modules/copy-webpack-plugin/dist/index.js:77:17)
    at /Users/sjh/Documents/tell2.0_megalo/node_modules/copy-webpack-plugin/dist/index.js:118:24
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tell2.0_megalo@0.0.0 dev:wechat: `webpack --config ./build/webpack.config.wechat.js -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tell2.0_megalo@0.0.0 dev:wechat script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sjh/.npm/_logs/2019-01-11T00_47_45_689Z-debug.log
➜  [/Us

**Comment by JH46666** [comment]
megalo current version:    0.3.2版本

npm list @megalo/template-compiler
├─┬ @megalo/target@0.5.5
│ └── @megalo/template-compiler@0.7.3  deduped
└── @megalo/template-compiler@0.7.3

**Comment by elcarim5efil** [comment]
上一个版本是多少？

**Comment by JH46666** [comment]
> 上一个版本是多少？

已解决
