### ISSUE TITLE
项目使用typescript版本编译成小程序后报错

### ISSUE THREAD

**Issue by zzzzzshPig** [kaola-fed/megalo#230]
报错内容如下：
thirdScriptError sdk uncaught third Error Function(...) is not a function TypeError: Function(...) is not a function
    at Object.node_modulesRegeneratorRuntimeRuntimeJs 
(http://127.0.0.1:44752/appservice/static/js/vendor.js:9685:46)
    at __webpack_require__ (http://127.0.0.1:44752/appservice/static/js/runtime.js:98:31)
    at Object.node_modulesBabelRuntimeRegeneratorIndexJs (http://127.0.0.1:44752/appservice/static/js/vendor.js:10:22)
    at __webpack_require__ (http://127.0.0.1:44752/appservice/static/js/runtime.js:98:31)
    at Module.srcStoreActionsTs (http://127.0.0.1:44752/appservice/static/js/app.js:347:87)
    at __webpack_require__ (http://127.0.0.1:44752/appservice/static/js/runtime.js:98:31)
    at Module.srcStoreIndexTs (http://127.0.0.1:44752/appservice/static/js/app.js:451:69)
    at __webpack_require__ (http://127.0.0.1:44752/appservice/static/js/runtime.js:98:31)
    at Object.srcIndexJs (http://127.0.0.1:44752/appservice/static/js/app.js:298:41)
    at __webpack_require__ (http://127.0.0.1:44752/appservice/static/js/runtime.js:98:31)

报错项目demo地址
https://github.com/zzzzzshPig/my-blog-ts.git

如果是使用这个demo，则没问题
https://github.com/zzzzzshPig/megalo-typescript-demo.git

没明白问题出在哪儿-=-求解答，谢谢。

**Comment by bigmeow** [comment]
昨天把对ts的解析器由babel换成了ts-loader
所以你之前拉的项目会报错，tsconfig.json的target必须是es5

**Comment by zzzzzshPig** [comment]
发现loader在处理import的时候有好大的问题啊

**Comment by zzzzzshPig** [comment]
问题找到了，不知道是不是配置的问题，无法使用async/await，一使用就报错。

**Comment by bigmeow** [comment]
删除nodo_modules 重新安装
再不行把小程序自带的es6转es5关掉就行

**Comment by zzzzzshPig** [comment]
components又编译不出来-=-，我决定暂时弃坑ts版本

**Comment by bigmeow** [comment]
target版本升级这个问题算解决了一半吧，还有一半在pullrequeat状态
