### ISSUE TITLE
执行sao npm:@megalo/cli megalo-demo报错

### ISSUE THREAD

**Issue by Jiasoh** [kaola-fed/megalo#272]
执行sao npm:@megalo/cli megalo-demo报错
环境：macOs 10.14
报错信息如下
sosodeMacBook-Pro:applets soso$ sao npm:@megalo/cli megalo-demo
/usr/local/lib/node_modules/sao/lib/index.js:52
  async run(generator, parent) {
        ^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at CAC.cli.command.action (/usr/local/lib/node_modules/sao/bin/cli.js:19:12)

**Comment by bigmeow** [comment]
node版本升级到9以上
