### ISSUE TITLE
npm run dev:wechat报错

### ISSUE THREAD

**Issue by smalldice** [kaola-fed/megalo#273]
(node:5838) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'unshift' of undefined
    at entryRuleArr.forEach (/Users/xiaojianhua/wechatxp/punch-card/node_modules/@megalo/target/lib/plugins/MegaloPlugin.js:240:43)
    at Array.forEach (<anonymous>)
    at hookCss (/Users/xiaojianhua/wechatxp/punch-card/node_modules/@megalo/target/lib/plugins/MegaloPlugin.js:238:16)
    at MegaloPlugin.apply (/Users/xiaojianhua/wechatxp/punch-card/node_modules/@megalo/target/lib/plugins/MegaloPlugin.js:53:5)
    at Object.target (/Users/xiaojianhua/wechatxp/punch-card/node_modules/@megalo/target/lib/index.js:23:33)
    at WebpackOptionsApply.process (/Users/xiaojianhua/wechatxp/punch-card/node_modules/webpack/lib/WebpackOptionsApply.js:217:12)
    at webpack (/Users/xiaojianhua/wechatxp/punch-card/node_modules/webpack/lib/webpack.js:53:48)
    at module.exports (/Users/xiaojianhua/wechatxp/punch-card/node_modules/@megalo/cli-service/lib/commands/serve/mpDevServer.js:15:20)
(node:5838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by elcarim5efil** [comment]
kaola-fed/megalo-aot#95
