### ISSUE TITLE
引入第三方 sdk 发生编译错误

### ISSUE THREAD

**Issue by yeojongki** [kaola-fed/megalo#278]
- 复现git:  https://github.com/yeojongki/megalo-im-test.git
- **问题**：
  - 初始化项目后引入环信的微信小程序 `sdk`，会报错，**报错信息在最下方**
  -  在一个 `uni-app` 项目上用同样的 `sdk`，可以运行不报错，附上 `git` 地址：https://github.com/yeojongki/uni-app.git ，因此猜测问题可能出现在 `babel` 的编译上?
- 版本：都是为最新，特意新建项目测试
- 系统： `win10 64` 位

报错信息：
```js
VM503:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot assign to read only property 'exports' of object '#<Object>' 
 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (http://127.0.0.1:45699/appservice/static/js/pages/hello.js:3334:16)
    at Module../src/static/sdk/connection.js (http://127.0.0.1:45699/appservice/static/js/pages/hello.js:3337:30)
    at __webpack_require__ (http://127.0.0.1:45699/appservice/static/js/runtime.js:79:30)
    at Module.<anonymous> (http://127.0.0.1:45699/appservice/static/js/pages/hello.js:13290:73)
    at Module../src/static/utils/WebIM.js (http://127.0.0.1:45699/appservice/static/js/pages/hello.js:13529:30)
    at __webpack_require__ (http://127.0.0.1:45699/appservice/static/js/runtime.js:79:30)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/@megalo/target/lib/frameworks/vue/loader/script.js!./node_modules/@megalo/target/lib/loaders/multi-platform-style.js!./node_modules/vue-loader/lib/index.js?!./src/pages/hello.vue?vue&type=script&lang=js& (http://127.0.0.1:45699/appservice/static/js/pages/hello.js:70:13)
    at __webpack_require__ (http://127.0.0.1:45699/appservice/static/js/runtime.js:79:30)
    at Module../src/pages/hello.vue?vue&type=script&lang=js& (http://127.0.0.1:45699/appservice/static/js/pages/hello.js:189:314)
    at __webpack_require__ (http://127.0.0.1:45699/appservice/static/js/runtime.js:79:30)
```

**Comment by yeojongki** [comment]
原因：`sdk` 中混用了 `import` & `module.exports ` ，修改就好了。
