### ISSUE TITLE
npm run dev:wechat报错：TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by zwkuang** [kaola-fed/megalo#287]
npm install 升级依赖包后
执行 npm run dev:wechat 会出现以下错误信息：

(node:19184) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
    at module.exports (D:\project\node_modules\@megalo\entry\lib\func\pagesEntry.js:59:20)
    at resolveEntry (D:\project\node_modules\@megalo\cli-plugin-mp\index.js:261:50)
    at api.chainWebpack.chainConfig (D:\project\node_modules\@megalo\cli-plugin-mp\index.js:34:57)
    at webpackChainFns.forEach.fn (D:\project\node_modules\@megalo\cli-service\lib\Service.js:242:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (D:\project\node_modules\@megalo\cli-service\lib\Service.js:242:26)
    at Service.resolveWebpackConfig (D:\project\node_modules\@megalo\cli-service\lib\Service.js:249:48)
    at PluginAPI.resolveWebpackConfig (D:\project\node_modules\@megalo\cli-service\lib\PluginAPI.js:110:25)
    at module.exports (D:\project\node_modules\@megalo\cli-service\lib\commands\serve\mpDevServer.js:14:29)
(node:19184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bigmeow** [comment]
已经修复，  运行 `npm upgrade` 更新下包即可
出错原因是包使用了es2019的语法，nodejs9\10 估计不支持
