### ISSUE TITLE
Megalo Demo 构建小程序失败

### ISSUE THREAD

**Issue by Lionad-Morotar** [kaola-fed/megalo#70]
### 描述

`npm run build:alipay` 和 `npm run build:swan` 报错, 报错信息如下:

``` js
TypeError: Cannot convert undefined or null to
object
    at Function.keys (<anonymous>)
    at module.exports (D:\@takecloud\megalo-demo\node_modules\@megalo\target\lib\platforms\shared\utils\composePlatformConfig.js:5:6)
    at Object.module.exports [as json] (D:\@takecloud\megalo-demo\node_modules\@megalo\target\lib\platforms\swan\codegen\page.json.js:4:19)
    at forEach.type (D:\@takecloud\megalo-demo\node_modules\@megalo\target\lib\platforms\shared\index.js:35:45)
    at Array.forEach (<anonymous>)
    at pages.forEach.options (D:\@takecloud\megalo-demo\node_modules\@megalo\target\lib\platforms\shared\index.js:34:50)
    at Array.forEach (<anonymous>)
    at D:\@takecloud\megalo-demo\node_modules\@megalo\target\lib\platforms\shared\index.js:26:11
    at compiler.hooks.emit.tap.compilation (D:\@takecloud\megalo-demo\node_modules\@megalo\target\lib\plugins\MegaloPlugin.js:96:7)
    at _err0 (eval at create (D:\@takecloud\megalo-demo\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:14:1)
    at callback (D:\@takecloud\megalo-demo\node_modules\copy-webpack-plugin\dist\index.js:77:17)
    at D:\@takecloud\megalo-demo\node_modules\copy-webpack-plugin\dist\index.js:118:24
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@1.0.0 build:swan: `webpack --config ./build/webpack.config.swan.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@1.0.0 build:swan script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lionad\AppData\Roaming\npm-cache\_logs\2018-12-07T03_20_27_708Z-debug.log
```

### 项目依赖

```json
"devDependencies": {
    "@megalo/entry": "^0.1.1",
    "@megalo/target": "^0.4.10",
    "@megalo/template-compiler": "^0.4.0",
    "babel-core": "6",
    "babel-loader": "^7.1.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "html-webpack-plugin": "^3.2.0",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.4.1",
    "vue": "^2.5.17",
    "vue-loader": "15.4.0",
    "vue-style-loader": "^4.1.1",
    "vue-template-compiler": "^2.5.17",
    "vuex": "^3.0.1",
    "webpack": "^4.26.0",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5"
  },
  "dependencies": {
    "@megalo/vhtml-plugin": "^0.1.0",
    "megalo": "^0.4.0",
    "octoparse": "^0.2.0"
  }
```

### 系统环境

| 环境 | 版本 |
| :---: | :---: |
| NPM | 6.1.0 |
| NodeJS | v10.4.0 |

**Comment by zwwill** [comment]
target 的问题，稍等，我们新发一版
