### ISSUE TITLE
默认安装的vue-template-compiler版本不匹配

### ISSUE THREAD

**Issue by owlikesj** [kaola-fed/megalo#77]
执行 `yarn run dev:wechat` 后报错
```shell
yarn run v1.6.0
$ webpack --config ./build/webpack.config.wechat.js -w
/Users/wangshijie/Lechebang/LcbMini/saas-mini/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

Error: 

Vue packages version mismatch:

- vue@2.5.20
- vue-template-compiler@2.5.17
```

执行 `npm list vue-template-compiler` 后输出
```
saas-mini@0.0.0 /Users/wangshijie/Lechebang/LcbMini/saas-mini
├─┬ @megalo/target@0.4.10
│ └─┬ @megalo/regular-template-compiler@0.1.1
│   └── vue-template-compiler@2.5.17 
└── vue-template-compiler@2.5.20 
```

发现是 @megalo/regular-template-compiler 的依赖写死 2.5.17 导致，其package.json内容如下
```json
{
  "name": "@megalo/regular-template-compiler",
  "version": "0.1.1",
  "description": "",
  "publishConfig": {
    "access": "public"
  },
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "html-minifier": "^3.5.21",
    "lodash.clonedeep": "^4.5.0",
    "nanoid": "^1.0.2",
    "prettier": "^1.13.4",
    "regularjs": "^0.6.0",
    "vue-template-compiler": "2.5.17",
    "loader-utils": "^1.1.0"
  },
  "devDependencies": {}
}
```

**Comment by elcarim5efil** [comment]
把 demo 里 vue 和 vue-template-compiler 去掉应该就好了，demo 工程对这两个包并没有依赖，多加了。谢谢反馈。

**Comment by owlikesj** [comment]
> 把 demo 里 vue 和 vue-template-compiler 去掉应该就好了，demo 工程对这两个包并没有依赖，多加了。谢谢反馈。

感谢回复

**Comment by qiuyaofan** [comment]
Error: 

Vue packages version mismatch:

- vue@1.0.21
- vue-template-compiler@2.5.17

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/qiuyaofan/Documents/lianxi/weixin/megalo-demo/node_modules/_vue-template-compiler@2.5.17@vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/qiuyaofan/Documents/lianxi/weixin/megalo-demo/node_modules/_@megalo_regular-template-compiler@0.3.0@@megalo/regular-template-compiler/index.js:1:90)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@1.0.0 dev:wechat: `node ./build/megalo-cli-service.js --mode development --platform wechat`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo@1.0.0 dev:wechat script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


去掉demo里的@megalo/regular-template-compiler "vue-template-compiler": "2.5.17",还是启动失败？
怎么解决？按照文档操作也启动不了

**Comment by elcarim5efil** [comment]
试下清除：packge-lock.json 和 node_modules 再试试呢？
