### ISSUE TITLE
通过megalo-cli生成的demo运行报错

### ISSUE THREAD

**Issue by NextBoy** [kaola-fed/megalo#81]
首次运行就报错。
ERROR in ./src/pages/hello.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/@megalo/target/lib/frameworks/vue/loader/script.js!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/hello.vue?vue&type=script&lang=js&)
Module build failed (from ./node_modules/@megalo/target/lib/frameworks/vue/loader/script.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/zzz/Documents/megalo-demo/node_modules/babel-preset-stage-0/lib/index.js
    at createDescriptor (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:162:11)
    at items.map (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at presets (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
    at presets (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:51:25)
    at mergeChainOpts (/Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:308:26)
    at /Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:271:7
    at buildRootChain (/Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:119:22)
    at loadPrivatePartialConfig (/Users/zzz/node_modules/@babel/core/lib/config/partial.js:51:55)
    at loadFullConfig (/Users/zzz/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/zzz/node_modules/@babel/core/lib/transform-sync.js:15:38)
    at Object.transform (/Users/zzz/node_modules/@babel/core/lib/transform.js:22:65)
    at module.exports (/Users/zzz/Documents/megalo-demo/node_modules/@megalo/target/lib/frameworks/shared/utils/extractCompilerOptionsFromScriptSource.js:16:30)
    at Object.module.exports (/Users/zzz/Documents/megalo-demo/node_modules/@megalo/target/lib/frameworks/vue/loader/script.js:15:5)
 @ ./src/pages/hello.vue?vue&type=script&lang=js& 1:0-235 1:251-254 1:256-488 1:256-488
 @ ./node_modules/vue-loader/lib??vue-loader-options!./src/pages/hello.vue
 @ ./src/pages/hello.vue

ERROR in ./src/app.js
Module build failed (from ./node_modules/@megalo/target/lib/loaders/js-entry.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/zzz/Documents/megalo-demo/node_modules/babel-preset-stage-0/lib/index.js
    at createDescriptor (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:162:11)
    at items.map (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at presets (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
    at presets (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:51:25)
    at mergeChainOpts (/Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:308:26)
    at /Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:271:7
    at buildRootChain (/Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:119:22)
    at loadPrivatePartialConfig (/Users/zzz/node_modules/@babel/core/lib/config/partial.js:51:55)
    at loadFullConfig (/Users/zzz/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/zzz/node_modules/@babel/core/lib/transform-sync.js:15:38)
    at Object.transform (/Users/zzz/node_modules/@babel/core/lib/transform.js:22:65)
    at Object.module.exports (/Users/zzz/Documents/megalo-demo/node_modules/@megalo/target/lib/loaders/js-entry.js:27:43)

ERROR in ./src/pages/my/index.js
Module build failed (from ./node_modules/@megalo/target/lib/loaders/js-entry.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/zzz/Documents/megalo-demo/node_modules/babel-preset-stage-0/lib/index.js
    at createDescriptor (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:162:11)
    at items.map (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at presets (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
    at presets (/Users/zzz/node_modules/@babel/core/lib/config/config-descriptors.js:51:25)
    at mergeChainOpts (/Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:308:26)
    at /Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:271:7
    at buildRootChain (/Users/zzz/node_modules/@babel/core/lib/config/config-chain.js:119:22)
    at loadPrivatePartialConfig (/Users/zzz/node_modules/@babel/core/lib/config/partial.js:51:55)
    at loadFullConfig (/Users/zzz/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/zzz/node_modules/@babel/core/lib/transform-sync.js:15:38)
    at Object.transform (/Users/zzz/node_modules/@babel/core/lib/transform.js:22:65)
    at Object.module.exports (/Users/zzz/Documents/megalo-demo/node_modules/@megalo/target/lib/loaders/js-entry.js:27:43)

**Comment by bigmeow** [comment]
找一下项目的父级，或者父级的父级，是否有node_modules目录存在，若有则干掉

**Comment by NextBoy** [comment]
@bigmeow 没有，重新初始化一个项目试了下，还是不行

**Comment by NextBoy** [comment]
目前已解决。
babel-core的需要做升级
