### ISSUE TITLE
megalo初始化的项目，打包微信小程序正常，百度和支付宝报错如下

### ISSUE THREAD

**Issue by NextBoy** [kaola-fed/megalo#84]
webpack is watching the files…

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (/Users/zzz/Documents/meglao-demo/node_modules/@megalo/target/lib/platforms/shared/utils/composePlatformConfig.js:5:6)
    at Object.module.exports [as json] (/Users/zzz/Documents/meglao-demo/node_modules/@megalo/target/lib/platforms/alipay/codegen/page.json.js:8:19)
    at forEach.type (/Users/zzz/Documents/meglao-demo/node_modules/@megalo/target/lib/platforms/shared/index.js:35:45)
    at Array.forEach (<anonymous>)
    at pages.forEach.options (/Users/zzz/Documents/meglao-demo/node_modules/@megalo/target/lib/platforms/shared/index.js:34:50)
    at Array.forEach (<anonymous>)
    at /Users/zzz/Documents/meglao-demo/node_modules/@megalo/target/lib/platforms/shared/index.js:26:11
    at compiler.hooks.emit.tap.compilation (/Users/zzz/Documents/meglao-demo/node_modules/@megalo/target/lib/plugins/MegaloPlugin.js:96:7)
    at _err0 (eval at create (/Users/zzz/Documents/meglao-demo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:14:1)
    at callback (/Users/zzz/Documents/meglao-demo/node_modules/copy-webpack-plugin/dist/index.js:77:17)
    at /Users/zzz/Documents/meglao-demo/node_modules/copy-webpack-plugin/dist/index.js:118:24
    at <anonymous>

**Comment by zwwill** [comment]
请允许 `megalo -v`，报一下版本

**Comment by zwwill** [comment]
请执行 `megalo -v`，报一下版本

**Comment by NextBoy** [comment]
@zwwill 0.3.0

**Comment by bigmeow** [comment]
@zwwill 最近版本问题提得挺多的，要不把模版的依赖的版本都改成`*`?
至少目前来说,版本变更频繁，让用户时刻保持最新

**Comment by zwwill** [comment]
@bigmeow 这样容易出现兼容问题

**Comment by NextBoy** [comment]
@bigmeow @zwwill 希望能同步更新脚手架生成的demo实例，现在运行有或多或少的问题，例如vue-templete-compiler和vue版本不匹配的问题，还有babel-core也存在版本问题

**Comment by bigmeow** [comment]
两者取其轻吧，现在在迭代频繁阶段，肯定是要更新到最新版的，在更新日志备注不兼容的api就行了
以后稳定下来了，通过版本号规范的控制来决定，目前这个阶段来说，我认为和megalo有关的库*更为合理

**Comment by bigmeow** [comment]
@NextBoy  自动更新的脚手架也不会去更新你的package.json文件，不过你这么说我倒是想到了一个主意，可以在脚手架里检查用户使用的megalo版本，提醒升级

**Comment by NextBoy** [comment]
@bigmeow 比如有个问题，我从脚手架拉取的demo，完全跑步起来，需要把babel-core全部升级到7，修改babelrc配置才行

**Comment by goldlin** [comment]
cli加个doctor之类的子命令，自动检查一下经过官方测试的依赖搭配，如何？

**Comment by elcarim5efil** [comment]
建议不错，减少以为依赖导致的工程配置问题。 大佬们觉得如何？@zwwill @bigmeow
